name: Lint, Unit, Non-snapshot tests
on:
  # allow for manual triggers
  workflow_dispatch: {}
  workflow_call: {}
  push:
    branches:
      - develop
  pull_request: {}

jobs:
  lintAndUnit:
    name: Lint and Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          persist-credentials: false
